### PR TITLE
#28: Support non-x86 architecture

### PR DESCRIPTION
**Pull request by galovics**

### CODE REVIEW

**Comment by Djelibeybi** [comment]
I'm on leave until early June, so I'll take a look next week. In the meantime, please remove the `.js` file from the PR, just leave the TypeScript file.

**Comment by galovics** [comment]
Will do @Djelibeybi, wasn't sure if that's needed so did the bundle generation anyway.

**Comment by Djelibeybi** [comment]
It may be worth waiting until I merge #32 which retrofits some CI stuff and bumps a bunch of dependencies to newer versions too.

**Comment by galovics** [comment]
@Djelibeybi sure thing, let me know when there's something to do for this PR.

**Review by tonybolzan — APPROVED** [review]

**Comment by Djelibeybi** [comment]
Sorry for the delay. I'm just in the middle of some internal changes which have resulted in the testing tenancy for these actions going away. I'm trying to find a replacement tenancy so that we can test these changes before merging.

**Comment by galovics** [comment]
alright, thanks for the update

**Comment by Djelibeybi** [comment]
Merged via #35

**Pull request closed without merging**
